<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <DebugSymbols>False</DebugSymbols>
        <DebugType>None</DebugType>
        <GenerateDependencyFile>false</GenerateDependencyFile>
        <PublishDir>./CS2_Admin_Grab/</PublishDir>
    </PropertyGroup>
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CounterStrikeSharp.API" Version="1.0.368">
            <PrivateAssets>none</PrivateAssets>
            <ExcludeAssets>runtime</ExcludeAssets>
            <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="back\**" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Remove="back\**" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="back\**" />
    </ItemGroup>

    <ItemGroup>
        <None Update="lang\**\*.*" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
